#!/usr/bin/env python3

Heads or Tails (Best out of 5)

import random

def flip_coin():
    "Flipping coin"
    return random.choice(['Heads', 'Tails'])
def play_game():
    "Plays best out of 5 Heads or Tails game"
    Player_score = 0
    Computure_score = 0

    while Player_score < 3 and Computer_score < 3:
        #Flips coing for Player and Computer
        Player_flip = Flips_coin()
        Computer_flip = Flips_coin()

        print("Player:", Player_flips)
        print("Computer", Computer_flips)

        #Determine the winner of this round
        if Player_flip == Computer_flip:
            print("It's a tie!")
        elif Player_flip == 'Heads' and Computer_flip == 'Tails':
            Player_score +=1
            print("Player wins this round!")
        else:
            Computer_score +=1
            print("Computer wins this round :(")

        print("Current score - Player:", Player_score, "Computer:", Computer_score)
        print()
    # Start the Game!
    play_game()

