#!/usr/bin/env python3

#Heads or Tails (Best out of 5)

import random

def flip_coin():
    #"Flipping coin"
    return random.choice(['Heads', 'Tails'])
def play_game():
    "Plays best out of 5 Heads or Tails game"
    player_score = 0
    computer_score = 0

    while Player_score < 3 and Computer_score < 3:
        #flips coing for player and computer
        player_flip = flips_coin()
        computer_flip = flips_coin()

        print("player:", player_flips)
        print("computer", computer_flips)

        #Determine the winner of this round
        if player_flip == computer_flip:
            print("It's a tie!")
        elif player_flip == 'Heads' and computer_flip == 'Tails':
            player_score +=1
            print("Player wins this round!")
        else:
            computer_score +=1
            print("Computer wins this round :(")

        print("current score - player:", player_score, "computer:", computer_score)
        print()
    
    # Start the Game!
    
    main()

